//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNMSolutions.DAL.DB.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int id { get; set; }
        public int SalesOrderID { get; set; }
        public int Terms { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public decimal AmountDue { get; set; }
        public bool isPaid { get; set; }
    }
}
