//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNMSolutions.DAL.DB.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_view
    {
        public int Id { get; set; }
        public int PONumber { get; set; }
        public int StockId { get; set; }
        public int SupplierId { get; set; }
        public int ProductId { get; set; }
        public string Brand { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal AcquisitionPrice { get; set; }
        public int PutAwayLocation { get; set; }
        public string ProductName { get; set; }
        public string CompanyName { get; set; }
    }
}
