//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNMSolutions.DAL.DB.Dev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MNMSolutionsDevDBEntities : DbContext
    {
        public MNMSolutionsDevDBEntities()
            : base("name=MNMSolutionsDevDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryOne> CategoryOnes { get; set; }
        public virtual DbSet<InventoryStock> InventoryStocks { get; set; }
        public virtual DbSet<ProductOne> ProductOnes { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual DbSet<SalesOrderHeader> SalesOrderHeaders { get; set; }
        public virtual DbSet<inventory_view> inventory_view { get; set; }
        public virtual DbSet<View_Category> View_Category { get; set; }
        public virtual DbSet<View_Product> View_Product { get; set; }
        public virtual DbSet<View_SalesOrderDetails> View_SalesOrderDetails { get; set; }
    
        public virtual int sp_orderdetail(Nullable<int> salesOrderID)
        {
            var salesOrderIDParameter = salesOrderID.HasValue ?
                new ObjectParameter("salesOrderID", salesOrderID) :
                new ObjectParameter("salesOrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_orderdetail", salesOrderIDParameter);
        }
    
        public virtual ObjectResult<sp_orderHeader_Result> sp_orderHeader(Nullable<int> soID)
        {
            var soIDParameter = soID.HasValue ?
                new ObjectParameter("soID", soID) :
                new ObjectParameter("soID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_orderHeader_Result>("sp_orderHeader", soIDParameter);
        }
    }
}
