//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNMSolutions.DAL.DB.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        public int SODetailsID { get; set; }
        public int SalesOrderID { get; set; }
        public int StockID { get; set; }
        public string SalesOrderNumber { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public string UOM { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
